name: 'Godot Publish to Itch.io'
description: 'Publishes exported build to Itch.io using Butler'

inputs:
  butler_api_key:
    description: 'Itch.io Butler API key'
    # API key for authenticating with Butler/Itch.io
    required: true

  build_path:
    description: 'Path to exported build'
    # Path to the exported build directory
    required: true
    default: "builds/web"

  itchio_target:
    description: 'Itch.io target (user/game:channel)'
    # Target in the format user/game:channel for Itch.io
    required: true

runs:
  using: 'composite'
  steps:
    - name: ðŸ§¾ Preflight Checklist ðŸ§¾
      run: |
        set -e
        echo "build_path: ${{ inputs.build_path }}"
        echo "itchio_target: ${{ inputs.itchio_target }}"
        echo "Contents of build_path:"
        ls -lh "${{ inputs.build_path }}"
      shell: bash

    - name: ðŸ›°ï¸ Downloading butler... ðŸ›°ï¸
      run: |
        set -e
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        echo "Butler downloaded. File details:"
        ls -lh butler.zip
      shell: bash

    - name: ðŸ“¡ Unpacking and Verifying Butler ðŸ“¡
      run: |
        set -e
        unzip butler.zip
        chmod +x butler
        echo "Butler version:"
        ./butler -V
      shell: bash

    - name: ðŸš€ Launch the Build to Itch.io ðŸš€
      run: |
        set -e
        echo "Pushing to Itch.io with Butler..."
        ./butler push "${{ inputs.build_path }}" "${{ inputs.itchio_target }}" --json > butler_output.json
        echo "Butler push output (summary):"
        cat butler_output.json | jq '.'
        echo "Butler push finished with status $?"
      env:
        BUTLER_API_KEY: ${{ inputs.butler_api_key }}
      shell: bash

    - name: ðŸ¦š Mission Debrief ðŸ¦š
      run: |
        set -e
        echo "Butler push summary:"
        if [ -f butler_output.json ]; then
          cat butler_output.json | jq '.'
        else
          echo "No butler_output.json found. See previous logs for details."
        fi
        echo "Files in build_path after upload:"
        ls -lh "${{ inputs.build_path }}"
      shell: bash
