name: 'Update Godot Project Versions'
description: 'Updates version information in Godot project files'
inputs:
  version:
    description: 'Version to set in project.godot (config/version)'

  project-file:
    description: 'Path to project.godot file'
    default: './project.godot'

  show-changes:
    description: 'Print .bak and updated file contents if true'
    default: false

runs:
  using: 'composite'
  steps:
    - name: Update project version
      if: ${{ inputs.version != '' }}
      run: |
        set -e
        file="${{ inputs.project-file }}"
        ver="${{ inputs.version }}"
        echo "Stamping version $ver in $file"
        
        file="${{ inputs.project-file }}"
        ver="${{ inputs.version }}"
        key="config/version"
        new_line="$key=\"$ver\""

        if grep -q "^$key=" "$file"; then
          sed -i.bak "s|^$key=.*|$new_line|" "$file"
        else
          sed -i.bak "/^config\/name=/a\\$new_line" "$file"
        fi
      shell: bash

    - name: Show changes
      if: ${{ inputs.show-changes == 'true' }}
      run: |
        echo "Original file:"
        cat "${{ inputs.project-file }}.bak"
        echo "Updated file:"
        cat "${{ inputs.project-file }}"
      shell: bash
