name: 'Godot Download Engine'
description: 'Downloads Godot engine binaries and export templates by tag from GitHub releases'

inputs:
  godot_release_tag:
    description: 'GitHub release tag for Godot engine (e.g., "4.4.1-stable")'
    # This should match the tag format used in Godot releases
    # For example, "4.4.1-stable" for Godot 4.4.1 stable release
    # https://github.com/godotengine/godot/tags
    default: "latest"

  target_release_asset:
    description: 'Target executable Godot engine from release(e.g., "linux.x86_64", "windows.x86_64")'
    # This should match the naming convention used in Godot releases
    # For example, "linux.x86_64" for Linux, "windows.x86_64" for Windows, etc.
    # https://github.com/godotengine/godot/releases
    default: "stable_linux.x86_64"

  output_path:
    description: 'Path and filename for the downloaded Godot executable'
    # Output path for the downloaded Godot binary
    # Leave this default if using the digiur `build-project` action
    default: "GodotEngine"

  use_mono_templates:
    # If set to true, make sure target_release_asset is a mono build
    description: 'If true, use the mono export templates; if false, use the standard templates'
    default: "false"

runs:
  using: 'composite'
  steps:
    - name: 📋 Inputs 📋
      run: |
        set -e
        echo "godot_release_tag: ${{ inputs.godot_release_tag }}"
        echo "target_release_asset: ${{ inputs.target_release_asset }}"
        echo "output_path: ${{ inputs.output_path }}"
        echo "use_mono_templates: ${{ inputs.use_mono_templates }}"
      shell: bash

    - name: 🛰️ Fetch Godot Release Data 🛰️
      run: |
        set -e
        if [ "${{ inputs.godot_release_tag }}" = "latest" ]; then
          echo "Fetching latest release..."
          GH_API="https://api.github.com/repos/godotengine/godot/releases/latest"
        else
          echo "Fetching release by tag: ${{ inputs.godot_release_tag }}"
          GH_API="https://api.github.com/repos/godotengine/godot/releases/tags/${{ inputs.godot_release_tag }}"
        fi

        echo "Using GitHub API endpoint: $GH_API"
        HTTP_RESPONSE=$(curl -s -w "\n%{http_code}" "$GH_API")
        HTTP_BODY=$(echo "$HTTP_RESPONSE" | head -n -1)
        HTTP_STATUS=$(echo "$HTTP_RESPONSE" | tail -n 1)

        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "❌ GitHub API returned an HTTP error status $HTTP_STATUS"
          echo "Response:"
          echo "$HTTP_BODY" | jq .
          exit 1
        fi

        if ! echo "$HTTP_BODY" | jq -e . >/dev/null 2>&1; then
          echo "❌ Response is not valid JSON:"
          echo "$HTTP_BODY"
          exit 1
        fi

        ERROR_MSG=$(echo "$HTTP_BODY" | jq -r .message)
        if [ "$ERROR_MSG" != "null" ]; then
          echo "❌ GitHub API error message: $ERROR_MSG"
          echo "$HTTP_BODY" | jq .
          exit 1
        fi

        # See https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release for example RELEASE_JSON
        RELEASE_JSON="$HTTP_BODY" # No errors! It is a release JSON!
        TAG_NAME=$(echo "$RELEASE_JSON" | jq -r .tag_name)
        echo "✅ Found release: $TAG_NAME"

        echo "RELEASE_JSON=$RELEASE_JSON" >> $GITHUB_ENV
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      shell: bash

    - name: 🎯 Find Engine Asset 🎯
      run: |
        set -e
        echo "Looking for engine asset matching: ${{ inputs.target_release_asset }}"

        ENGINE_URL_COUNT=$(echo "$RELEASE_JSON" | jq -r --arg ast "${{ inputs.target_release_asset }}" '[.assets[] | select(.name | test($ast + "\\.zip$"))] | length')

        if [ "$ENGINE_URL_COUNT" -eq 0 ]; then
          echo "❌ No asset found matching target_release_asset: '${{ inputs.target_release_asset }}'"
          echo "Available engine assets:"
          echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | endswith(".zip")) | .name'
          exit 1
        elif [ "$ENGINE_URL_COUNT" -gt 1 ]; then
          echo "❌ More than one asset matched target_release_asset: '${{ inputs.target_release_asset }}'"
          echo "Matches:"
          echo "$RELEASE_JSON" | jq -r --arg ast "${{ inputs.target_release_asset }}" '.assets[] | select(.name | test($ast + "\\.zip$")) | .name'
          exit 1
        fi

        ENGINE_URL=$(echo "$RELEASE_JSON" | jq -r --arg ast "${{ inputs.target_release_asset }}" '.assets[] | select(.name | test($ast + "\\.zip$")) | .browser_download_url')
        echo "✅ Found engine URL: $ENGINE_URL"
        echo "ENGINE_URL=$ENGINE_URL" >> $GITHUB_ENV
      shell: bash

    - name: 📦 Find Templates Asset 📦
      run: |
        set -e
        if [ "${{ inputs.use_mono_templates }}" = "true" ]; then
          echo "Looking for mono export templates..."
          TEMPLATES_COUNT=$(echo "$RELEASE_JSON" | jq -r '[.assets[] | select(.name | contains("mono") and endswith("export_templates.tpz"))] | length')
          EXPECTED_TYPE="mono"
        else
          echo "Looking for standard export templates..."
          TEMPLATES_COUNT=$(echo "$RELEASE_JSON" | jq -r '[.assets[] | select(.name | endswith("export_templates.tpz") and (contains("mono") | not))] | length')
          EXPECTED_TYPE="standard"
        fi

        if [ "$TEMPLATES_COUNT" -eq 0 ]; then
          echo "❌ No $EXPECTED_TYPE export templates found"
          echo "Available template assets:"
          echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | endswith("export_templates.tpz")) | .name'
          exit 1
        elif [ "$TEMPLATES_COUNT" -gt 1 ]; then
          echo "❌ Multiple $EXPECTED_TYPE export templates found"
          echo "Matches:"
          if [ "${{ inputs.use_mono_templates }}" = "true" ]; then
            echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | contains("mono") and endswith("export_templates.tpz")) | .name'
          else
            echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | endswith("export_templates.tpz") and (contains("mono") | not)) | .name'
          fi
          exit 1
        fi

        if [ "${{ inputs.use_mono_templates }}" = "true" ]; then
          TEMPLATES_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | contains("mono") and endswith("export_templates.tpz")) | .browser_download_url')
        else
          TEMPLATES_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | endswith("export_templates.tpz") and (contains("mono") | not)) | .browser_download_url')
        fi

        echo "✅ Found templates URL: $TEMPLATES_URL"

        echo "TEMPLATES_URL=$TEMPLATES_URL" >> $GITHUB_ENV
      shell: bash

    - name: 📡 Download Engine and Templates 📡
      run: |
        set -e
        echo "Downloading engine: $ENGINE_URL"
        curl -L --fail "$ENGINE_URL" -o godot.zip
        echo "Downloading export templates: $TEMPLATES_URL"
        curl -L --fail "$TEMPLATES_URL" -o templates.tpz
      shell: bash

    - name: 🪄 Extract Engine and Templates 🪄
      run: |
        set -e
        unzip -j -q godot.zip -d .

        # Templates archive should contain a 'templates/' directory
        unzip -q templates.tpz -d .

        # Godot expects 3.6.1-stable → 3.6.1.stable for the templates directory name
        TEMPLATES_DIR=$(echo "$TAG_NAME" | sed 's/-/./g')
        EXECUTABLE=$(find . -maxdepth 1 -type f -name "Godot*${{ inputs.target_release_asset }}*" | head -n1)

        if [ -z "$EXECUTABLE" ]; then
          echo "❌ Could not find extracted Godot executable matching 'Godot*${{ inputs.target_release_asset }}*'"
          exit 1
        fi

        mv "$EXECUTABLE" "${{ inputs.output_path }}"

        echo "Engine binary moved to ${{ inputs.output_path }}"

        mkdir -p ~/.local/share/godot/export_templates/"$TEMPLATES_DIR"

        if [ -d "templates" ]; then
          mv templates/* ~/.local/share/godot/export_templates/"$TEMPLATES_DIR"/
          echo "Export templates installed to: ~/.local/share/godot/export_templates/$TEMPLATES_DIR"
          ls -lh ~/.local/share/godot/export_templates/"$TEMPLATES_DIR"
        else
          echo "❌ Templates directory not found after extraction"
          exit 1
        fi
      shell: bash
